
[package]
name = "aoc_2015"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
dinglebit_combinatorics = "1.1.0"
hex-literal = "1.0.0"
itertools = "0.14.0"
md-5 = "0.10.6"
nom = "8.0.0"
rayon = "1.11.0"
serde_json = "1.0.143"
